version: "3.8"
services:
  users-services:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    image: postgres:latest
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwer1234
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data